apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-cluster
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-client
  labels:
    istio-injection: enabled
